name: Upload Website

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@master

    - name: Build Project
      run: |
        npm ci
        npm run build --if-present

    # Upload to S3 bucket
    - name: AWS S3 Deployment
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.MFC_AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.MFC_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.MFC_AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'dist/website'      # optional: defaults to entire repository

    # Invalidate Cloudfront
    - name: Invalidate Cloudfront Cache
      uses: chetan/invalidate-cloudfront-action@master
      env:
        DISTRIBUTION: ${{ secrets.MFC_DISTRIBUTION }}
        PATHS: '/*'
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.MFC_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.MFC_AWS_SECRET_ACCESS_KEY }}
